;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-sub-or-superscript
        abort-recursive-edit
        backward-sexp
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        delete-indentation
        down-list
        end-of-visual-line
        forward-sentence
        forward-sexp
        indent-for-tab-command
        mark-sexp
        nispio/strip-1
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-insert-heading-respect-content
        org-metaright
        org-open-line
        phi-rectangle-kill-region
        phi-rectangle-kill-ring-save
        phi-rectangle-yank
        phi-search
        python-nav-backward-up-list
        sgml-slash
        sh-assignment
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        avy-goto-word-or-subword-1
        handle-select-window
        helm-M-x
        ignore
        mc/toggle-cursor-on-click
        mc/vertical-align-with-space
        menu-bar-open
        multiple-cursors-mode
        nispio/compile-c
        nispio/mc-many-cursors
        ))
